Hide VSCode button when printing
Mottie/GitHub-userscripts pull request #164
Opened 2022-01-05 20:35 UTC by stdedos

Fixes https://github.com/Mottie/GitHub-userscripts/issues/163

Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>

2022-01-05 20:36 UTC, stdedos commented
@Mottie I hope you don't mind a PR. It's been manually tested to work; but I am unsure if you like `GM_addStyle` (or if you like its location)

2022-01-06 01:20 UTC, Mottie requested changes

2022-01-06 01:20 UTC, Mottie commented on github-in-vscode.user.js
> +
Hi @stdedos! Thanks for taking the time to submit this PR.

I think it'd be easier to use the built-in `GM_addStyle`. Add this line after the `@include`:

```js
// @grant       GM_addStyle
```

2022-01-06 16:44 UTC, stdedos commented on github-in-vscode.user.js
> +
Technically speaking,

```js
// @grant       GM_addStyle
```

Is not available in Tampermonkey (https://www.tampermonkey.net/documentation.php#_grant, https://stackoverflow.com/a/33176845) 😕

2022-01-06 16:52 UTC, darkred commented on github-in-vscode.user.js
> +
Of course it is available in TM. In the first page you linked there's: https://www.tampermonkey.net/documentation.php#GM_addStyle
You just have to declare it explicitly `// @grant  GM_addStyle`

2022-01-06 16:56 UTC, stdedos commented on github-in-vscode.user.js
> +
Ooops 😅 Thank you for the fact-checking

2022-01-06 17:04 UTC, Mottie commented on github-in-vscode.user.js
> +
I see it here - https://www.tampermonkey.net/documentation.php#GM_addStyle - the accepted Stack Overflow answer says you need to include the `@grant GM_addStyle` otherwise you see that error

2022-01-06 21:43 UTC, Mottie approved these changes
Thanks again!

2022-01-06 21:43 UTC, merged

2022-01-06 22:43 UTC, Mottie commented on github-in-vscode.user.js
> +
Oops, my computer has been laggy all day and I didn't see the last 2 messages until now LOL... thanks @darkred!

2022-07-28 00:27 UTC, fulyagroupstone commented on README.md
> +	| [GitHub in VSCode][ivs-wiki]           |     | [install][ivs-raw] | [GF][ivs-gf] [OU][ivs-ou] | 2021.02.11 | 2022.01.05 |
|