Fix button appearance
Mottie/GitHub-userscripts pull request #184
Opened 2023-03-08 00:15 UTC by neoOpus

Now button appears as the default GH

2023-03-08 00:23 UTC, Mottie requested changes

2023-03-08 00:23 UTC, Mottie commented on github-rtl-comments.user.js
> +			button.type = "md-code";
Thanks for your work, but `md-code` is specific to the code button. Please change these two lines back to `button`.

2023-03-20 11:36 UTC, Mottie commented
Thanks!

2023-03-20 11:36 UTC, merged

2023-03-20 11:48 UTC, neoOpus commented
> Thanks!

Thank you for the merge and for letting me know about the md-code... right now I am trying to make this work with this extension [GitHub Writer - Chrome Web Store (google.com)](https://chrome.google.com/webstore/detail/github-writer/diilnnhpcdjhhkjcbdljaonhmhapadap) as it add some nice features too but breaks some userscripts including this one...

2023-03-20 23:08 UTC, Mottie commented
Nice extension! I'll take a look when I have some free time (which is rare 😿)